### ISSUE TITLE
nwjs error

### ISSUE THREAD

**Issue by tommy7600** [node-hid/node-hid#106]
Hi,
when trying to use with the latest nwjs I'm getting an error:

52122:0916/140855:ERROR:nw_shell.cc(335)] Error: Module version mismatch. Expected 43, got 14.
    at Error (native)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:356:17)
    at require (module.js:375:17)
    at Object.<anonymous> (/private/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/.org.chromium.Chromium.9BmkRs/node_modules/node-hid/index.js:5:15)
    at Module._compile (module.js:451:26)
    at Object.Module._extensions..js (module.js:469:10)
    at Module.load (module.js:346:32)
    at Function.Module._load (module.js:301:12)

On console it works ok

**Comment by tommy7600** [comment]
Solution:
Go to node-hid folder and run ./nw-gyp rebuild --target=0.12.3
