### ISSUE TITLE
Cant build on raspberry pi with raspbian jesse

### ISSUE THREAD

**Issue by Zazcallabah** [node-hid/node-hid#124]
It doesn't seem to use the result of the build command.

the result of `./node_modules/.bin/node-pre-gyp rebuild`

ends with

      COPY /home/pi/tmp/node-hid/build/HID/v0.5.1/Release/node-v46-linux-arm/HID.node
      TOUCH Release/obj.target/action_after_build.stamp
    make: Leaving directory '/home/pi/tmp/node-hid/build'
    gyp info ok
    node-pre-gyp info ok

but when i try to run one of the examles:

    pi@raspberrypi:~/tmp/node-hid/src $ nodejs show-devices.js
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module '/home/pi/tmp/node-hid/build/HID/v0.5.1/Release/node-v11-linux-arm/HID.node'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at Object.<anonymous> (/home/pi/tmp/node-hid/nodehid.js:9:15)
        at Module._compile (module.js:456:26)
        at Object.Module._extensions..js (module.js:474:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:312:12)
        at Module.require (module.js:364:17)

What decides if it should look for node-v11 or node-v46?

**Comment by Zazcallabah** [comment]
Ok, it seems to have something to do with me having a really outdated version of node hiding under the nodejs binary. (v0.10.29)
When forcing v4.2.2 it works. Closing this issue.
