### ISSUE TITLE
cannot open device with vendor id .... on raspberry

### ISSUE THREAD

**Issue by pauapau** [node-hid/node-hid#204]
hey i#m using rasbian and want to receive data from a usb scale.
my script is working on windows but not on raspian

when i start the script with sudo i will get this error
`Error: cannot open device with vendor id 0x922 and product id 0x8003
    at Error (native)
    at new HID (/home/pi/Scale/node_modules/node-hid/nodehid.js:28:17)
    at Object.<anonymous> (/home/pi/Scale/usb.js:9:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
`

the vid and pid is right

here is my script:
```
var hid = require('node-hid');
var vid=0x922,
pid=0x8003;
 
var devices = hid.devices();
 try {
	var d = new hid.HID(vid, pid);
 }
catch(err){
    console.log(err);
}
```

**Comment by fsegouin** [comment]
Same error here on raspberry pi 3 (armv7) & raspbian.
