### ISSUE TITLE
Cannot install node-hid on Windows 10 with node 6.11.2

### ISSUE THREAD

**Issue by vsdigitall** [node-hid/node-hid#220]
**Hello, when run installation process via command: 'npm install node-hid', I receive the following errors:**

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\job\\node\\node.exe" "C:\\job\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-hid"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-hid@0.5.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.5.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-hid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-hid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-hid
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\job\node\npm-debug.log

**LOG from npm-debug.log:**
7353 verbose stack Error: node-hid@0.5.4 install: `node-pre-gyp install --fallback-to-build`
7353 verbose stack Exit status 1
7353 verbose stack     at EventEmitter.<anonymous> (C:\job\node\node_modules\npm\lib\utils\lifecycle.js:255:16)
7353 verbose stack     at emitTwo (events.js:106:13)
7353 verbose stack     at EventEmitter.emit (events.js:191:7)
7353 verbose stack     at ChildProcess.<anonymous> (C:\job\node\node_modules\npm\lib\utils\spawn.js:40:14)
7353 verbose stack     at emitTwo (events.js:106:13)
7353 verbose stack     at ChildProcess.emit (events.js:191:7)
7353 verbose stack     at maybeClose (internal/child_process.js:891:16)
7353 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
7354 verbose pkgid node-hid@0.5.4
7355 verbose cwd C:\job\node
7356 error Windows_NT 10.0.15063
7357 error argv "C:\\job\\node\\node.exe" "C:\\job\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-hid"
7358 error node v6.11.2
7359 error npm  v3.10.10
7360 error code ELIFECYCLE
7361 error node-hid@0.5.4 install: `node-pre-gyp install --fallback-to-build`
7361 error Exit status 1
7362 error Failed at the node-hid@0.5.4 install script 'node-pre-gyp install --fallback-to-build'.
7362 error Make sure you have the latest version of node.js and npm installed.
7362 error If you do, this is most likely a problem with the node-hid package,
7362 error not with npm itself.
7362 error Tell the author that this fails on your system:
7362 error     node-pre-gyp install --fallback-to-build
7362 error You can get information on how to open an issue for this project with:
7362 error     npm bugs node-hid
7362 error Or if that isn't available, you can get their info via:
7362 error     npm owner ls node-hid
7362 error There is likely additional logging output above.
7363 verbose exit [ 1, true ]

**Can you please give me any suggestions how to install node-hid on my system?**

**Comment by vsdigitall** [comment]
Guys, problem was solved by:
1. installing python 2.7
2. adding node & python paths to PATH environmental variable
3. optional SET PYTHON=<path_to_python> before running **npm install node-hid**
