### ISSUE TITLE
cannot open device problem

### ISSUE THREAD

**Issue by perython** [node-hid/node-hid#264]
Hello,

I'm trying to connect to the rfid reader device using node-hid@0.7.2
When I connect the device to the macbook (OS 10.13.4) I can see it in the System information -> USB.
`ps aux | grep reader` gives me:
```
root             79882   0.0  0.1  4324988   9000   ??  Ss    9:48AM   0:00.02 /System/Library/CryptoTokenKit/com.apple.ifdreader.slotd/Contents/MacOS/com.apple.ifdreader
```
This is a driver for the device as I can understand and I think it shouldn't conflict with node-hid.

Then in the node I do usual:
```
var HID = require('node-hid')
var readerDevice = HID.devices().find(d => d.product.startsWith('Barcode'))
if (readerDevice) {
  console.log(readerDevice)
  var reader = new HID.HID(readerDevice.path)
}
```
it gives me:
```
{ vendorId: 5050,
  productId: 24,
  path: 'IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14200000/Barcode Reader @14200000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14200000,0',
  serialNumber: '',
  manufacturer: '',
  product: 'Barcode Reader ',
  release: 1,
  interface: -1,
  usagePage: 1,
  usage: 6 }
Error: cannot open device with path IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/XHC1@14/XHC1@14000000/HS05@14200000/Barcode Reader @14200000/IOUSBHostInterface@0/IOUSBHostHIDDevice@14200000,0
    at new HID (/Users/perython/projects/electron-serialport/node_modules/node-hid/nodehid.js:54:17)
    at repl:1:10
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at REPLServer.defaultEval (repl.js:240:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:441:10)
    at emitOne (events.js:121:20)
    at REPLServer.emit (events.js:211:7)
    at REPLServer.Interface._onLine (readline.js:282:10)
```

Could you please help me with this? Are there any other checks I might have missed?

**Comment by perython** [comment]
I just solved my own problem:
`sudo node` - now I can connect to the device :)
