### ISSUE TITLE
Error while packaging a 32bit electron app in a 64bit Win10 machine

### ISSUE THREAD

**Issue by DeekshithShetty** [node-hid/node-hid#279]
Hi, I get the following error when I try to package my app to a 32 bit installer on a 64bit Windows 10 version. 

`prebuild-install WARN install No prebuilt binaries found (target=2.0.8 runtime=electron arch=ia32 platform=win32)`

I am using `electron-builder` for handling packaging. My `postinstall` npm script has `electron-builder install-app-deps`. Packaging to a 64bit works fine.

Electron version used: 2.0.8
node-hid version used: 0.7.3

Any idea why this is happening?

Stack trace is as below:
````
Unhandled rejection Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> node-hid@0.7.3 install D:\My Repos\my-desktop-app\node_modules\node-hid
> prebuild-install || node-gyp rebuild

D:\My Repos\my-desktop-app\node_modules\node-hid>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )

Error output:
prebuild-install WARN install No prebuilt binaries found (target=2.0.8 runtime=electron arch=ia32 platform=win32)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\My Repos\my-desktop-app\node_modules\node-hid
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.7.3 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
````

**Comment by DeekshithShetty** [comment]
Updating `electron-builder` to `20.28.4` seems to have fixed this issue.
