### ISSUE TITLE
An error occurred while packing with electroni-forge make

### ISSUE THREAD

**Issue by xiajingren** [node-hid/node-hid#401]
> electron-vue-demo@1.0.0 make D:\WorkSpace\Temp\electron-vue-demo
> electron-forge make

√ Checking your system
√ Resolving Forge Config
We need to package your application before we can make it
√ Preparing to Package Application for arch: x64
√ Compiling Application
× Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:207:27)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\WorkSpace\\Temp\\electron-vue-demo\\node_modules\\electron-forge\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=8.2.0" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\xiajr\AppData\Local\Temp\electron-packager\win32-x64\electron-vue-demo-win32-x64\resources\app\node_modules\node-hid
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onStreamRead (internal/stream_base_commons.js:207:27)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\WorkSpace\\Temp\\electron-vue-demo\\node_modules\\electron-forge\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=8.2.0" "--arch=x64" "--dist-url=https://www.electronjs.org/headers" "--build-from-source"
gyp ERR! cwd C:\Users\xiajr\AppData\Local\Temp\electron-packager\win32-x64\electron-vue-demo-win32-x64\resources\app\node_modules\node-hid
gyp ERR! node -v v14.7.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:143:22)
    at Subscriber._next (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:89:26)
    at Subscriber.next (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:66:18)
    at DefaultIfEmptySubscriber._next (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\operators\defaultIfEmpty.js:41:26)
    at DefaultIfEmptySubscriber.Subscriber.next (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:66:18)
    at TakeLastSubscriber._complete (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\operators\takeLast.js:71:29)
    at TakeLastSubscriber.Subscriber.complete (D:\WorkSpace\Temp\electron-vue-demo\node_modules\electron-forge\node_modules\rxjs\internal\Subscriber.js:78:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-vue-demo@1.0.0 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-vue-demo@1.0.0 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xiajr\AppData\Roaming\npm-cache\_logs\2020-09-26T12_47_13_385Z-debug.log
PS D:\WorkSpace\Temp\electron-vue-demo> npm run make

**Comment by xiajingren** [comment]
my bad. package.json "scripts" add "postinstall": "electron-rebuild"
