### ISSUE TITLE
Issues trying to work with Elgato Stream Deck MK

### ISSUE THREAD

**Issue by jmorris644** [node-hid/node-hid#456]
I have tried many things to get the Elgato StreamDeck working. I am running Ubuntu server 20.04 on a Pi 3B+.

The first thing I did was to create a rules file and reload the rules. I know that it worked because the /dev/hidraw0 file was created. Here is the contents of my rules file
```
SUBSYSTEM=="input", GROUP="input", MODE="0666"
SUBSYSTEM=="usb", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="666", GROUP="plugdev"
KERNAL=="hidraw*", ATTRS{idVendor}=="0fd9", ATTRS{idProduct}=="0080", MODE:="0666", GROUP="plugdev"
```
For reference, here is the lsusb output:
```
Bus 001 Device 005: ID 0fd9:0080 Elgato Systems GmbH
Bus 001 Device 004: ID 0424:7800 Microchip Technology, Inc. (formerly SMSC)
Bus 001 Device 003: ID 0424:2514 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Microchip Technology, Inc. (formerly SMSC) USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
I then used show-devices.js to do some testing. 

I ran show-device.js without any modifications and it worked find and displayed the streamdeck at /dev/hidraw0

I then added the statement "hidDevice = new HID.HID(/dev/hidraw0);" to the end of show-devices.js and got the error:
```
/home/joe/test/node_modules/node-hid/nodehid.js:49
    this._raw = new (Function.prototype.bind.apply(binding.HID,
                ^

TypeError: cannot open device with path /dev/hidraw0
    at new HID (/home/joe/test/node_modules/node-hid/nodehid.js:49:17)
    at Object.<anonymous> (/home/joe/test/node_modules/node-hid/src/show-devices.js:17:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```

I then did a chmod of 666 to /dev/hidraw0, reran show-devices and it worked great. No errors.

Because the streamdeck (elgato) uses setDriverType('libusb") I then added that line in the show-devices.js and changed the new line to '0001:0005:00' which is the result of HID.devices() after setting the driver type. Running it I get this error:
```
node: ../../libusb/io.c:2146: handle_events: Assertion `ctx->pollfds_cnt >= internal_nfds' failed.
Aborted (core dumped)
```
I noticed that after this error /dev/hidraw0 does not exist anymore. The only way I could get it back was to reboot.
I do not know where to go form here to get the device type of libusb to work.

**Comment by Julusian** [comment]
I remember seeing this error, but have no idea when or why...
It might have been when node exited, and closing the hid device. Or removing/stopping the 'input' event listener.

To make the device visible to hidraw again, the easiest way is to unplug and replug it.
I don't know why you are having issues, I havent tried on a pi in a while, but I havent had any issues with streamdecks on x64 linux
