### ISSUE TITLE
No Suitable Image Found

### ISSUE THREAD

**Issue by matthewkremer** [node-hid/node-hid#66]
Installation runs fine, however, when using I get this:

    Uncaught node.js Error 
    
    Error: dlopen(/Users/matthewkremer/Documents/GameViewer/node_modules/node-hid/build/Release/HID.node, 1): no suitable image found.  Did find:
    /Users/matthewkremer/Documents/GameViewer/node_modules/node-hid/build/Release/HID.node: mach-o, but wrong architecture
        at Module.load (module.js:352:32)
        at Function.Module._load (module.js:308:12)
        at Module.require (module.js:360:17)
        at require (module.js:376:17)
        at Object.eval (/Users/matthewkremer/Documents/GameViewer/node_modules/node-hid/index.js:5:15)
        at Module._compile (module.js:452:26)
        at Object.Module._extensions..js (module.js:470:10)
        at Module.load (module.js:352:32)
        at Function.Module._load (module.js:308:12)
        at Module.require (module.js:360:17)

If it matters, I'm running OSX 10.10 right now. I'm fairly new to using Node/node-webkit, so please let me know if there is any additional information you need to help me out.

Thanks!
Matt

**Comment by natevw** [comment]
Can you try this again with node-hid@0.4.0? My guess as to the original problem was upgrading node without using `npm rebuild`, but updating to the latest should also serve to resolve that and any more recent node 0.12.x incompatibility trouble.
